### ISSUE TITLE
Error en entidad Opina al sacar JSON

### ISSUE THREAD

**Issue by luiscode18** [ereme/smartquercus#11]
Al intentar obtener el JSON de opina devuelve el siguiente error, relacionado con la entidad de Opina:

**_Argument 1 passed to App\Entity\Opina::getHaVotado() must be an instance of App\Entity\Vecino, null given, called in src/Controller/OpinaController.php on line 285_**

El error se refiere a lo siguiente:
```
foreach ($opinas as $key => $value) {
    $value->getHaVotado($this->getUser());
}
```

Al no estar logueado no es posible acceder al usuario mediante getUser().

**Posible solución temporal:**
Pasar en la ruta también el userID para manejar esa parte: opina/json/{aytoID}/{userID}

**Comment by jmunozco** [comment]
Hecho el cambio y probado. Prueba y cierra.

```
[{
	"id": 3,
	"pregunta": "Pregunta1",
	"votosfavor": 2,
	"porcentajeFavor": 10,
	"activo": false,
	"votoscontra": 18,
	"porcentajeContra": 90,
	"ayuntamiento": "Alburquerque",
	"imagen": "https:\/\/localhost:8000\/images\/46ade374a24b02346f73dbb992e53a2f",
	"fechahoralimite": "25-12-2018"
}, {
	"id": 4,
	"pregunta": "Pregunta 2",
	"votosfavor": 1,
	"porcentajeFavor": 33,
	"activo": false,
	"votoscontra": 2,
	"porcentajeContra": 67,
	"ayuntamiento": "Alburquerque",
	"imagen": "https:\/\/localhost:8000\/images\/ad6b5d0e07278e1f78181ef8b9b8bd23",
	"fechahoralimite": "28-12-2018"
}]
```

**Comment by luiscode18** [comment]
Funcionando correctamente en la app.
