### ISSUE TITLE
JSON e imagen de recientes (json_inicio)

### ISSUE THREAD

**Issue by luiscode18** [ereme/smartquercus#2]
La imagen que devuelve "recientes" (json_inicio) contiene todos los datos, pero se esperaba solamente la dirección directa a la imagen.

El JSON que devuelve "recientes" (json_inicio) contiene doble array o parece estar mal estructurado. Al acceder a él desde la app no responde correctamente.

El JSON que devuelve sería este:
```
[
	[{
		"id": 1,
		"titular": "Evento1 Alburquerque",
		"fechahora": "18-12-2018",
		"texto": "Evento1",
		"imagen": {
			"id": 12,
			"nombre": "4a1ddc0c09c7336319f5e04d965f6563",
			"original": "sqljoins.png",
			"createdAt": "26-12-2018",
			"size": 162672,
			"__initializer__": null,
			"__cloner__": null,
			"__isInitialized__": true
		},
		"ayuntamiento": "Alburquerque"
	}, {
		"id": 2,
		"titular": "ffasdf",
		"fechahora": "25-12-2018",
		"texto": "gaasdfasdf",
		"imagen": {
			"id": 16,
			"nombre": "8b08111761872a2a3d4d6bce344a9449",
			"original": "sqljoins.png",
			"createdAt": "26-12-2018",
			"size": 162672,
			"__initializer__": null,
			"__cloner__": null,
			"__isInitialized__": true
		},
		"ayuntamiento": "Alburquerque"
	}],
	[]
]
```

En lugar de ese, debería de ser algo tal que así:
```
[
	{
		"id": 1,
		"titular": "Evento1 Alburquerque",
		"fechahora": "18-12-2018",
		"texto": "Evento1",
		"imagen": "https://url-to-image",
		"ayuntamiento": "Alburquerque"
	}, {
		"id": 2,
		"titular": "ffasdf",
		"fechahora": "25-12-2018",
		"texto": "gaasdfasdf",
		"imagen": "https://url-to-image",
		"ayuntamiento": "Alburquerque"
	}
]
```

**Comment by jmunozco** [comment]
Se ha modificado RecientesController, de momento con salud y eventos. 

El json generado de prueba es este:
`[{
	"id": 1,
	"titular": "Evento1 Alburquerque",
	"fechahora": "18-12-2018",
	"texto": "Evento1",
	"nombre": "https:\/\/localhost:8000\/images\/4a1ddc0c09c7336319f5e04d965f6563",
	"localidad": "Alburquerque"
}, {
	"id": 2,
	"titular": "ffasdf",
	"fechahora": "25-12-2018",
	"texto": "gaasdfasdf",
	"nombre": "https:\/\/localhost:8000\/images\/8b08111761872a2a3d4d6bce344a9449",
	"localidad": "Alburquerque"
}, {
	"id": 1,
	"titulo": "No tomes az\u00facar",
	"fechahora": "21-01-2019",
	"texto": "No es bueno tomar azucar",
	"nombre": "https:\/\/localhost:8000\/images\/8d02feac8bd22cfd111cc4287c83c64f",
	"1": "NULL"
}]`

Probar y cerrar si todo ok.

**Comment by jmunozco** [comment]
Solucionado en siguiente subida
