### ISSUE TITLE
Access Denied JSON Salud

### ISSUE THREAD

**Issue by luiscode18** [ereme/smartquercus#6]
Al intentar acceder al JSON de salud se deniega el acceso.

_Access denied. (403 Forbidden)_

Ocurre independientemente de si el usuario está logueado o no.

Línea 176 del [Controlador de Salud](https://github.com/ereme/smartquercus/blob/master/src/Controller/SaludController.php). Solo permite el acceso a los usuarios administradores.

```
/** 
 * @Route("/json", name="json_salud")
 * @Security("has_role('ROLE_ADMIN')")  <-- THIS
 */
```

**Comment by jmunozco** [comment]
Resuelto en próxima subida.
