### ISSUE TITLE
[WEB] Error acceso perfil usuario

### ISSUE THREAD

**Issue by luiscode18** [ereme/smartquercus#8]
Al intentar acceder al perfil del usuario logueado desde la web, se produce el siguiente error que impide el acceso a dicha sección.

**_Impossible to access an attribute ("nombre") on a null variable._**

El error hace referencia a la línea número 63 del [template show de User](https://github.com/ereme/smartquercus/blob/master/templates/user/show.html.twig).

```
<img class="img" src="{{ asset(app.user.ayuntamiento.imagen.nombre, 'usuarios') }}" alt="Card image cap" height="200" width="200">
```

**Comment by jmunozco** [comment]
Corrected.
