### ISSUE TITLE
[WEB] Error seguridad /user/{id}/edit

### ISSUE THREAD

**Issue by luiscode18** [ereme/smartquercus#9]
Al acceder a la ruta **_/user/{id}/edit_**, donde ID es el ID de un usuario, y estando previamente logueado, permite acceder y editar el perfil de otros usuarios.

**Comportamiento esperado (posible)**

- Si eres el usuario 40 y accedes a **_/user/40/edit_** te permite editar tu propio perfil de usuario.

- Sin embargo, si accedes a **_/user/10/edit_** te envía a otra página diferente (sin permitirte editar el perfil de ese usuario).

**Comment by jmunozco** [comment]
Corrected.

**Comment by luiscode18** [comment]
He vuelto a probarlo y parece que el error permanece.

Siendo usuario con ID 46 he probado a acceder a:
/user/40
/user/40/edit

He podido ver los datos de ese otro usuario y modificarlos.
